version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: pip install -r requirements.txt

  test:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Run Unit Tests
          command: pytest

  build-docker:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: docker build -t $mehdibadami/circleci-test-app:latest .

  push-docker:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Login to Docker Hub
          command: echo "$dckr_pat_pwTFDfIdozwkXLpihQ3CVODib9E" | docker login -u "$mehdibadami" --password-stdin
      - run:
          name: Push Docker Image
          command: docker push $mehdibadami/circleci-test-app:latest

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - test
      - build-docker
      - push-docker:
          requires:
            - build-docker
